[package]
name = "curlall"
version = "0.1.0"
authors = ["Robin Stocker"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
serde_json = "*"
structopt = "*"

[dev-dependencies]
hyper = "*"
